---

- name: Provision application web server
  hosts: webservers
  become: true
  become_user: root
  remote_user: "{{ server_user }}"
  vars:
    update_apt_cache: true
  vars_files:
    group_vars/production/vars.yml
  module_defaults:
    ansible.builtin.apt:
      force_apt_get: true

  roles:
    - base
    - certbot
    # - rabbitmq
    - web
    - nginx
    # - celery
